### PR TITLE
Hello React-Rails app

### PR DESCRIPTION
**Pull request by mikemtzp**
# :memo: Project Description
> The Hello Rails-React app is a first approach to using simultaneously Rails and React in the same project using the `jsbundling-rails` gem configured with Webpack. The app displays a random greeting from a PostgreSQL database. Built with Ruby on Rails and React.js.

### Back-end
- Create a new Rails app called 'hello-rails-react'.
- Use the commend `rails new -j webpack my_new_rails_app` as described in [this tutorial](https://medium.com/better-programming/react-with-rails-2022-bd28e1fcd355).
- Verify that the `jsbundling-rails` gem is added to your Gemfile.
- Initialize your project with Git.
- Install needed node dependencies as described in the previous lesson's tutorial.
- Create a `babel.config.js` in the root folder of your project as described in the previous lesson's tutorial.
- Update `webpack.config.js` to include the babel loader as described in the previous lesson's tutorial.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
- Create a static view that will be the root of your app.

<hr>

### Front-end
- Create the `App` component with react-router and render it in your static view.
- Create the `Greeting` component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Display the random greeting in your `Greeting` component.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @mikemtzp 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow the proper [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mikemtzp** [comment]
Hi, @prolajumokeoni!
Thanks for taking the time for reviewing my project. 😁
The project follows the proper [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) as this PR is requested to be merged from the `development` branch into the `main` branch. Also, all the other `feature` branches were correctly merged previously into the `development` branch.

**Comment by prolajumokeoni** [comment]
> Hi @mikemtzp,  carefully read through the instructions to use proper [Gitflow](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/rails_react_webpack.md#general-requirements) and when [opening pull request](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md#opening-pull-requests) under the project requirement, `You will need to create a pull request to compare your feature branch with the development branch and submit the link to that pull request via your Dashboard`

**Review by Munsa1 — APPROVED** [review]
Hi @mikemtzp, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikemtzp** [comment]
@prolajumokeoni I have checked how to use proper Gitflow and understand your point:
> Once you start working on any project, initialize its main branch. You also need to create a development branch. Then you need to make your development branch [the default branch](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch). 
After that, add changes in a feature branch(es). You will need to create a pull request to compare your feature branch with the development branch and submit the link to that pull request via your Dashboard.

My mistake, sorry for the misunderstanding and thanks for the feedback. 😁

**Pull request merged**
